# Generated by Django 4.2 on 2026-04-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_baritem_slug_remove_menuitem_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcategory',
            options={'verbose_name_plural': 'Bar Categories'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='hookah',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
