# Generated by Django 4.2 on 2026-04-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_reservation_end_time_reservation_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP / Privat Cupe')], default='standard', max_length=20),
        ),
    ]
