# Generated by Django 4.2 on 2026-04-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_table_table_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
    ]
